apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: learningcenter-portal
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Developer Workshops
    password: VMware1!
    registration:
      type: anonymous
      enabled: true
    updates:
      workshop: true
    sessions:
      maximum: 45
  workshops:
    - name: tanzu-developer-workshop
      expires: 360m
      orphaned: 120m
      capacity: 15
      reserved: 0
